version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.8
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/users:/mosquitto/config/users
      - ~/docker-volumes/mosquitto/data:/mosquitto/data
      - ~/docker-volumes/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/docker-volumes/influxdb:/var/lib/influxdb
    restart: always

    telegraf:
      image: telegraf:1.13-alpine
      container_name: telegraf
      ports:
        - 8125:8125
        - 8092:8092
        - 8094:8094
      volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
#   grafana:
#     image: grafana/grafana:5.4.3
#     container_name: grafana
#     depends_on:
#       - influxdb
#     ports:
#       - 3000:3000
#     volumes:
#       - ~/docker-volumes/grafana:/var/lib/grafana
#     restart: always

#   mqttbridge:
#     build: ./02-bridge
#     image: nilhcem/mqttbridge
#     container_name: mqttbridge
#     depends_on:
#       - mosquitto
#       - influxdb
#     restart: always
